name: ShopSphere QA

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

  schedule:
    # - cron: "30 2 * * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results -o allure-report --clean

      - name: Setup GitHub Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report/

      - name: Deploy Allure Report
        if: always()
        uses: actions/deploy-pages@v4